# Generated by Django 5.2.12 on 2026-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_workversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
