# Generated by Django 5.2.13 on 2026-04-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_worksection_work_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='visibility',
            field=models.CharField(choices=[('private', 'Открытая'), ('public', 'Скрытая')], default='private', max_length=20),
        ),
    ]
